OUTPUT_PATH=./Debug
OBJS=main.o unit_test.o src/hammers_and_nails.o src/math_helpers.o

INC_PATH=/usr/local/include
LIB_PATH=/usr/local/lib

export CPP_FLAGS=-g -Wall -O3 -I/usr/local/include
export LD_FLAGS=-L/usr/local/lib
export LIBS=-lfftw3 -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d     \
            -lopencv_objdetect -lopencv_contrib -lopencv_legacy -lopencv_flann
export CC=g++
export LINKER=g++

ALL:cityu-wavelets-2.0
	
cityu-wavelets-2.0:$(OBJS)
	$(LINKER) -o $@  $(OBJS) $(LIBS) $(LD_FLAGS)


%.o:%.cpp
	$(CC) -o $@ $(CPP_FLAGS) -c $<

#Be careful to modify this rule, since it may remove files which should NOT be removed.
clean:
	-rm -r $(OBJS) cityu-wavelets-2.0
	
